version: "3.8"

services:
  dpms-web:
    image: isresearch/dpms-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped
